// Autogenerated code from https://app.quicktype.io using a real response from the coinbase API.
// I used a real resposne because the json example response from the API docs did not work.

// To parse this JSON data, do
//
//     final coinbaseProAccounts = coinbaseProAccountsFromJson(jsonString);

import 'dart:convert';

List<CoinbaseProAccounts> coinbaseProAccountsFromJson(String str) =>
    List<CoinbaseProAccounts>.from(
        json.decode(str).map((x) => CoinbaseProAccounts.fromJson(x)));

String coinbaseProAccountsToJson(List<CoinbaseProAccounts> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class CoinbaseProAccounts {
  CoinbaseProAccounts({
    this.id,
    this.currency,
    this.balance,
    this.available,
    this.hold,
    this.profileId,
    this.tradingEnabled,
  });

  String id;
  String currency;
  String balance;
  String available;
  String hold;
  String profileId;
  bool tradingEnabled;

  factory CoinbaseProAccounts.fromJson(Map<String, dynamic> json) =>
      CoinbaseProAccounts(
        id: json["id"],
        currency: json["currency"],
        balance: json["balance"],
        available: json["available"],
        hold: json["hold"],
        profileId: json["profile_id"],
        tradingEnabled: json["trading_enabled"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "currency": currency,
        "balance": balance,
        "available": available,
        "hold": hold,
        "profile_id": profileId,
        "trading_enabled": tradingEnabled,
      };
}
